export const users = [{
    id: 1,
    pic: "pic-male-1.jpg",
    firstName: "Jerry",
    lastName: "Rice",
    team: "Accounting",
    role: "Admin",
    emailAddress: "jrice@email.com",
    phoneNumber: "555-555-5555",
    userName: 'jrice',
    isActive: true,
    userName: "jrice",
    isMfaActive: true,
    products: [{
        streamlineX: true,
        workFlowPro: true,
        teamSync: true,
        pulseMetrics: false
    }]
}, {
    id: 2,
    pic: "pic-male-2.jpg",
    firstName: "Tim",
    lastName: "Brown",
    team: "Technology",
    role: "User",
    emailAddress: "tbrown@email.com",
    phoneNumber: "555-555-5555",
    userName: 'tbrown',
    isActive: true
}, {
    id: 3,
    pic: "pic-male-3.jpg",
    firstName: "Sterling",
    lastName: "Sharpe",
    team: "Production",
    role: "User",
    emailAddress: "ssharpe@email.com",
    phoneNumber: "555-555-5555",
    userName: 'ssharpe',
    isActive: false
}]